{"uid":"ec125320526cb93b","name":"Переход в раздел 'Выбрать специалиста'","fullName":"tests.test_main_page.TestMainPage#test_specialists_section","historyId":"e46dce0177082dd8d9b7e5f4d727a06b","time":{"start":1761163595026,"stop":1761163595026,"duration":0},"status":"broken","statusMessage":"playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nPlease use the Async API instead.","statusTrace":">   ???\n\nC:\\Users\\user\\effective-mobile-autotests\\conftest.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.10/dist-packages/playwright/sync_api/_context_manager.py:84: in start\n    return self.__enter__()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright.sync_api._context_manager.PlaywrightContextManager object at 0x744ae28f91e0>\n\n        def __enter__(self) -> SyncPlaywright:\n            try:\n                self._loop = asyncio.get_running_loop()\n            except RuntimeError:\n                self._loop = asyncio.new_event_loop()\n                self._own_loop = True\n            if self._loop.is_running():\n>               raise Error(\n                    \"\"\"It looks like you are using Playwright Sync API inside the asyncio loop.\n    Please use the Async API instead.\"\"\"\n                )\nE               playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nE               Please use the Async API instead.\n\n/usr/local/lib/python3.10/dist-packages/playwright/sync_api/_context_manager.py:47: Error","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"base_url","time":{"start":1761163593926,"stop":1761163593926,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":0,"attachmentStep":false,"hasContent":false},{"name":"delete_output_dir","time":{"start":1761163593926,"stop":1761163593926,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":0,"attachmentStep":false,"hasContent":false},{"name":"_verify_url","time":{"start":1761163593926,"stop":1761163593926,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":0,"attachmentStep":false,"hasContent":false},{"name":"pytestconfig","time":{"start":1761163593926,"stop":1761163593926,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":0,"attachmentStep":false,"hasContent":false},{"name":"browser","time":{"start":1761163595026,"stop":1761163595026,"duration":0},"status":"broken","statusMessage":"playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nPlease use the Async API instead.\n","statusTrace":"  File \"/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/usr/local/lib/python3.10/dist-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/dist-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\user\\effective-mobile-autotests\\conftest.py\", line 8, in browser\n  File \"/usr/local/lib/python3.10/dist-packages/playwright/sync_api/_context_manager.py\", line 84, in start\n    return self.__enter__()\n  File \"/usr/local/lib/python3.10/dist-packages/playwright/sync_api/_context_manager.py\", line 47, in __enter__\n    raise Error(\n","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":true,"stepsCount":0,"attachmentStep":false,"hasContent":true}],"afterStages":[],"labels":[{"name":"suite","value":"Главная страница effective-mobile.ru"},{"name":"feature","value":"Проверка навигации"},{"name":"parentSuite","value":"tests"},{"name":"subSuite","value":"TestMainPage"},{"name":"host","value":"7d8d826181e1"},{"name":"thread","value":"7-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_main_page"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"ec125320526cb93b.json","parameterValues":[]}